// Open-Meteo 지오코딩이 한글 지명을 잘 인식하지 못하는 주요 도시들의
// 한글 표기 -> 영문 검색어 매핑 (검색 매칭용, 화면 표시는 language=ko 응답을 그대로 사용)
export const KOREAN_CITY_ALIASES = {
  서울: 'Seoul',
  부산: 'Busan',
  인천: 'Incheon',
  대구: 'Daegu',
  대전: 'Daejeon',
  광주: 'Gwangju',
  울산: 'Ulsan',
  수원: 'Suwon',
  제주: 'Jeju',

  도쿄: 'Tokyo',
  오사카: 'Osaka',
  교토: 'Kyoto',
  삿포로: 'Sapporo',
  베이징: 'Beijing',
  상하이: 'Shanghai',
  홍콩: 'Hong Kong',
  마카오: 'Macau',
  타이베이: 'Taipei',
  방콕: 'Bangkok',
  싱가포르: 'Singapore',
  쿠알라룸푸르: 'Kuala Lumpur',
  자카르타: 'Jakarta',
  하노이: 'Hanoi',
  호치민: 'Ho Chi Minh City',
  마닐라: 'Manila',
  뉴델리: 'New Delhi',
  뭄바이: 'Mumbai',
  두바이: 'Dubai',

  런던: 'London',
  파리: 'Paris',
  베를린: 'Berlin',
  로마: 'Rome',
  마드리드: 'Madrid',
  바르셀로나: 'Barcelona',
  암스테르담: 'Amsterdam',
  취리히: 'Zurich',
  빈: 'Vienna',
  프라하: 'Prague',
  모스크바: 'Moscow',
  이스탄불: 'Istanbul',
  아테네: 'Athens',

  뉴욕: 'New York',
  로스앤젤레스: 'Los Angeles',
  시카고: 'Chicago',
  샌프란시스코: 'San Francisco',
  라스베이거스: 'Las Vegas',
  토론토: 'Toronto',
  밴쿠버: 'Vancouver',

  시드니: 'Sydney',
  멜버른: 'Melbourne',
  오클랜드: 'Auckland',

  카이로: 'Cairo',
  요하네스버그: 'Johannesburg',
  상파울루: 'Sao Paulo',
  리우데자네이루: 'Rio de Janeiro',
  부에노스아이레스: 'Buenos Aires',
  멕시코시티: 'Mexico City',
}
